# Site settings
title: Css-Hacker's Personal Website
github_username: Css-Hacker
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/css-hacker/css-hacker.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/css-hacker/css-hacker.github.io/new/master
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
